spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/rocket_tx1?serverTimezone=GMT%2B8
    username: root
    password: 721000
    type: com.zaxxer.hikari.HikariDataSource
  cloud:
    consul:
      discovery:
        enabled: true
        service-name: order-service
      host: 127.0.0.1
      port: 8500

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


server:
  port: 8081

mybatis:
  type-aliases-package: com.tang.stock.domain
  mapper-locations: classpath:/mapper/*.xml


rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: rocket-tx-group